# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StocksExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StocksExample
  pod 'PinLayout'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'NetworkService', :path => '../../NetworkService'
  pod 'Stocks', :path => '../'

end
